# used for ZIH HPC systems
srun --nodes=1 --gres=gpu:1 --time=01:00:00 --pty bash
cd /data/horse/ws/rosc...
module load release/23.04 GCC/11.3.0 OpenMPI/4.1.4 CUDAcore/11.5.1 PyTorch/1.12.1
python -m venv --system-site-packages my-env
source my-torch-env/bin/activate
pip install ...

cd fuzzing_...
python Fuzzer/main.py config...
deactivate